language: node_js
node_js:
  - "10"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - cd frontend
  - npm install -g @angular/cli

script:
- npm run build:test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/work-calendar
  on:
    branch: master
